Repository CS2103-AY1819S1-W14-3/main, pull requests merged in 2018-10, with the labels that each got.

#33 Refactor add to checkin
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckinCommandParser.java
  src/test/java/seedu/address/logic/commands/CheckinCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckinCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/CheckinCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High, type.Enhancement

#34 Replace .jpg with .png
  docs/AboutUs.adoc
  docs/images/gaojiaxin666.png
  docs/images/jeffypie369.png
  docs/images/omegafishy.png
  docs/images/snajef.png
  docs/images/yuntongzhang.png
Labels: priority.High

#28 Add NRIC functionality to PersonCard
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High, type.Enhancement

#29 Feature/documentation
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
Labels: type.Enhancement

#36 Feature/checkin
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckinCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/CheckinCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckinCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/CheckinCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High, type.Enhancement

#32 Feature/addmeds+viewmeds
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddmedsCommand.java
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/logic/parser/AddmedsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medicine/Dose.java
  src/main/java/seedu/address/model/medicine/Duration.java
  src/main/java/seedu/address/model/medicine/Prescription.java
  src/main/java/seedu/address/model/medicine/PrescriptionList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedPrescription.java
  src/main/java/seedu/address/storage/XmlAdaptedPrescriptionList.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/css/MedTable.css
  src/main/resources/view/BrowserPanel.fxml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/commands/AddmedsCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddmedsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/medicine/DoseTest.java
  src/test/java/seedu/address/model/medicine/DurationTest.java
  src/test/java/seedu/address/model/medicine/PrescriptionListTest.java
  src/test/java/seedu/address/model/medicine/PrescriptionTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPrescriptionListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPrescriptionTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionUtil.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.High, type.Enhancement

#41 Bootstrap adddiet command
  src/main/java/seedu/address/logic/commands/AddDietCommand.java
  src/main/java/seedu/address/logic/parser/AddDietCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/AddDietCommandTest.java
  src/test/java/seedu/address/logic/parser/AddDietCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#42 Feature/addmh
  .gitattributes
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddmhCommand.java
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/logic/commands/ViewmhCommand.java
  src/main/java/seedu/address/logic/parser/AddmhCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewmhCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/medicalhistory/Diagnosis.java
  src/main/java/seedu/address/model/medicalhistory/MedicalHistory.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddmhCommandTest.java
  src/test/java/seedu/address/logic/parser/AddmhCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewmhCommandParserTest.java
  src/test/java/seedu/address/testutil/DiagnosisBuilder.java
  src/test/java/seedu/address/testutil/DiagnosisUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Enhancement

#75 Feature/documentation
  docs/DeveloperGuide.adoc
  docs/images/AddmedsSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/systemtests/CheckinCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High

#86 Update DeveloperGuide for addmh and viewmh feature, include sequence …
  docs/DeveloperGuide.adoc
  docs/diagrams/AddmhViewmh SequenceDiagram.png
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/images/AddmhViewmh SequenceDiagram.png
  src/main/java/seedu/address/model/medicalhistory/MedicalHistory.java
Labels: priority.High

#76 Add fully functional adddiet Command
  src/main/java/seedu/address/logic/commands/AddDietCommand.java
  src/main/java/seedu/address/logic/parser/AddDietCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/diet/Diet.java
  src/main/java/seedu/address/model/diet/DietCollection.java
  src/main/java/seedu/address/model/diet/DietType.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddDietCommandTest.java
  src/test/java/seedu/address/logic/commands/AddmedsCommandTest.java
  src/test/java/seedu/address/logic/commands/AddmhCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddDietCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/diet/DietCollectionTest.java
  src/test/java/seedu/address/model/diet/DietTest.java
Labels: priority.High, type.Enhancement

#85 Feature/documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/AddmedsSequenceDiagram.pptx
  docs/images/AddmedsSequenceDiagram.png
Labels: severity.Low, type.Task

#77 AddApptCommand
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AdddietSequenceDiagram.pptx
  docs/images/AddApptSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddmedsCommand.java
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentsList.java
  src/main/java/seedu/address/model/appointment/DateTime.java
  src/main/java/seedu/address/model/appointment/Type.java
  src/main/java/seedu/address/model/appointment/TypeFields.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointmentsList.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddApptCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/AppointmentsListTest.java
  src/test/java/seedu/address/model/appointment/TypeFieldsTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAppointmentsListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Enhancement

#83 Add documentation for `adddiet` command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AdddietSequenceDiagram.png
Labels: priority.High, type.Task

#88 Update role and responsibility, fix typo in docs
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.Medium

#82 Feature/addmeds+viewmeds
  src/main/java/seedu/address/model/medicine/Duration.java
  src/main/java/seedu/address/storage/XmlAdaptedDose.java
  src/main/java/seedu/address/storage/XmlAdaptedDuration.java
  src/main/java/seedu/address/storage/XmlAdaptedPrescription.java
  src/main/java/seedu/address/storage/XmlAdaptedPrescriptionList.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/model/medicine/DurationTest.java
  src/test/java/seedu/address/model/medicine/PrescriptionListTest.java
  src/test/java/seedu/address/model/medicine/PrescriptionTest.java
  src/test/java/seedu/address/storage/XmlAdaptedDoseTest.java
  src/test/java/seedu/address/storage/XmlAdaptedDurationTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPrescriptionListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPrescriptionTest.java
  src/test/java/seedu/address/testutil/PrescriptionBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionUtil.java
Labels: priority.Medium, type.Task

#98 Fix failing test in DietCollectionTest
  src/test/java/seedu/address/model/diet/DietCollectionTest.java
Labels: severity.High, type.Bug

#97 Feature/documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/UiMock.png
  docs/images/blankPanel.png
  docs/images/highlightUserViewLocation.png
  docs/images/medsView.png
Labels: priority.High

#73 Feature/refactor
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/AddmhCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewmhCommandTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
  src/test/java/seedu/address/model/diet/DietCollectionTest.java
Labels: priority.Medium, type.Task

#79 Feature/visitorin
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/seedu/address/logic/commands/VisitorInCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/VisitorInCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/visitor/Visitor.java
  src/main/java/seedu/address/model/visitor/VisitorList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/VisitorInCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/VisitorInCommandParserTest.java
  src/test/java/seedu/address/model/visitor/VisitorListTest.java
  src/test/java/seedu/address/model/visitor/VisitorTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/VisitorBuilder.java
  src/test/java/seedu/address/testutil/VisitorUtil.java
Labels: priority.High

#104 Update version number to v1.2.1
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#107 Update name of built jar file
  build.gradle
Labels: priority.High

#109 Feature/documentation
  docs/UserGuide.adoc
  docs/images/HighlightIndex.png
Labels: priority.High

#110 Feature/visitor in
  src/main/java/seedu/address/logic/commands/VisitorinCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/VisitorinCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/visitor/VisitorList.java
  src/test/java/seedu/address/logic/commands/VisitorInCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/VisitorInCommandParserTest.java
  src/test/java/seedu/address/model/visitor/VisitorListTest.java
  src/test/java/seedu/address/testutil/VisitorUtil.java
Labels: priority.High

#106 Feature/project-portfolio-page
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/snajef.adoc
Labels: priority.High, severity.Low

#112 Feature/addmeds+viewmeds
  src/main/java/seedu/address/logic/commands/AddmedsCommand.java
  src/main/java/seedu/address/logic/parser/AddmedsCommandParser.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/ui/MedicationView.java
Labels: priority.Medium

#119 Add AppointmentView and check nric functionality
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/model/appointment/AppointmentsList.java
  src/main/java/seedu/address/ui/AppointmentView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MedicationView.java
  src/main/java/seedu/address/ui/SwappablePanelName.java
  src/main/resources/view/ApptBrowserPanel.fxml
  src/test/java/guitests/guihandles/AppointmentViewHandle.java
  src/test/java/seedu/address/logic/commands/CheckinCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/AppointmentViewTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/CheckinCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High

#120 Add addmh UI functionality
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/AddmedsCommand.java
  src/main/java/seedu/address/logic/commands/ViewmhCommand.java
  src/main/java/seedu/address/model/medicalhistory/Diagnosis.java
  src/main/java/seedu/address/model/medicalhistory/MedicalHistory.java
  src/main/java/seedu/address/model/medicalhistory/Timestamp.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedDiagnosis.java
  src/main/java/seedu/address/storage/XmlAdaptedMedicalHistory.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/HistoryView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SwappablePanelName.java
  src/main/resources/view/HistoryPanel.fxml
  src/test/java/guitests/guihandles/HistoryViewHandle.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/ViewmhCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedDiagnosisTest.java
  src/test/java/seedu/address/storage/XmlAdaptedMedicalHistoryTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/HistoryViewTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: priority.High, severity.Low

#122 Diet view
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/diet/DietCollection.java
  src/main/java/seedu/address/ui/DietView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SwappablePanelName.java
  src/main/resources/view/DietPanel.fxml
  src/test/java/guitests/guihandles/DietViewHandle.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/DietViewTest.java
  src/test/java/seedu/address/ui/SwappablePanelNameTest.java
Labels: priority.High
