Repository CS2103-AY1819S1-W14-3/main, pull requests merged in 2018-11, with the labels that each got.

#128 Add ppp for yuntongzhang
  docs/UserGuide.adoc
  docs/team/yuntongzhang.adoc
Labels: priority.High, type.Task

#130 Feature/project portfolio page
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/AddmedsSequenceDiagram.png
  docs/images/highlightUserViewLocation.png
  docs/team/snajef.adoc
Labels: priority.High

#132 Refactored application name to HealthBase, update documentation
  README.adoc
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  docs/team/omegafishy.adoc
  docs/templates/_header.html.slim
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/hospital-icon-png-12.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Task

#170 Update asciidoc website header
  build.gradle
  docs/templates/_header.html.slim
Labels: type.Task

#169 Feature/sort+view
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: priority.High

#141 Minor fixes for snajef ppp
  docs/UserGuide.adoc
  docs/images/apptView.png
  docs/images/dietView.png
  docs/images/mhView.png
Labels: priority.High

#172 Fix bug from AddmhCommand
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medicalhistory/Diagnosis.java
Labels: priority.High, severity.Medium, type.Bug, type.Task

#168 Feature/addmeds+viewmeds
  src/main/java/seedu/address/logic/commands/AddmedsCommand.java
  src/main/java/seedu/address/logic/parser/AddmedsCommandParser.java
Labels: priority.High

#188 Feature/project portfolio page
  docs/DeveloperGuide.adoc
  docs/team/snajef.adoc
Labels: priority.High

#180 Clean up code, add extra test
  src/main/java/seedu/address/logic/commands/ViewmhCommand.java
  src/main/java/seedu/address/logic/parser/AddmhCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewmhCommandParser.java
  src/main/java/seedu/address/model/medicalhistory/MedicalHistory.java
  src/main/java/seedu/address/storage/XmlAdaptedMedicalHistory.java
  src/main/java/seedu/address/ui/HistoryView.java
  src/test/java/seedu/address/logic/commands/ViewmhCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewmhCommandParserTest.java
  src/test/java/seedu/address/model/medicalhistory/DiagnosisTest.java
  src/test/java/seedu/address/storage/XmlAdaptedDiagnosisTest.java
  src/test/java/seedu/address/testutil/DiagnosisBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#183 Update UGDG for yuntongzhang
  docs/UserGuide.adoc
  docs/diagrams/AdddietSequenceDiagram.pptx
  docs/images/AdddietSequenceDiagram.png
  docs/team/yuntongzhang.adoc
Labels: priority.High, type.Task

#190 Fix formatting of UserGuide
  docs/UserGuide.adoc
Labels: priority.High

#189 Feature/refactor person
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddDietCommand.java
  src/main/java/seedu/address/logic/commands/AddmedsCommand.java
  src/main/java/seedu/address/logic/commands/AddmhCommand.java
  src/main/java/seedu/address/logic/commands/GendataCommand.java
  src/main/java/seedu/address/logic/commands/VisitorinCommand.java
  src/main/java/seedu/address/logic/commands/VisitoroutCommand.java
  src/main/java/seedu/address/model/diet/DietCollection.java
  src/main/java/seedu/address/model/medicine/PrescriptionList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/visitor/Visitor.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#199 Change filename of "HighlightIndex.png" to "highlightIndex.png" so th…
  docs/images/highlightIndex.png
Labels: priority.High

#177 Add XmlAdaptedTimestamp
  build.gradle
  src/main/java/seedu/address/model/medicalhistory/Timestamp.java
  src/main/java/seedu/address/storage/XmlAdaptedDiagnosis.java
  src/main/java/seedu/address/storage/XmlAdaptedTimestamp.java
  src/test/java/seedu/address/storage/XmlAdaptedTimestampTest.java
Labels: priority.High, status.Ongoing, type.Bug

#206 Feature/generate-data
  src/main/java/seedu/address/model/person/DataGenerator.java
Labels: priority.High

#209 Refactor `*Command#execute` and equality definition of `Person`
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddDietCommand.java
  src/main/java/seedu/address/logic/commands/AddmedsCommand.java
  src/main/java/seedu/address/logic/commands/AddmhCommand.java
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/logic/commands/CheckoutCommand.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/commands/ViewmhCommand.java
  src/main/java/seedu/address/logic/commands/ViewvisitorsCommand.java
  src/main/java/seedu/address/logic/commands/VisitorinCommand.java
  src/main/java/seedu/address/logic/commands/VisitoroutCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDietCommandTest.java
  src/test/java/seedu/address/logic/commands/AddmedsCommandTest.java
  src/test/java/seedu/address/logic/commands/AddmhCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckoutCommandTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewmhCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewvisitorsCommandTest.java
  src/test/java/seedu/address/logic/commands/VisitorInCommandTest.java
  src/test/java/seedu/address/logic/commands/VisitoroutCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High, type.Bug

#205 Feature/addmeds+viewmeds
  src/main/java/seedu/address/logic/parser/AddmedsCommandParser.java
Labels: priority.High

#212 Feature/documentation
  docs/UserGuide.adoc
Labels: priority.High

#213 Feature/project portfolio page
  docs/team/snajef.adoc
Labels: priority.High

#214 Add input validation to adddiet command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/diet/Diet.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#221 Set up Reposense configuration
  .gitignore
  _reposense/config.json
Labels: priority.High, type.Task

#208 Feature/viewvisitor+visitorout
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/visitorsView.png
  docs/team/gaojiaxin.adoc
  src/main/java/seedu/address/logic/commands/VisitoroutCommand.java
  src/main/java/seedu/address/model/visitor/VisitorList.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedVisitor.java
  src/main/java/seedu/address/storage/XmlAdaptedVisitorList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SwappablePanelName.java
  src/main/java/seedu/address/ui/VisitorView.java
  src/main/resources/view/VisitorPanel.fxml
  src/test/java/guitests/guihandles/VisitorViewHandle.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedVisitorListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedVisitorTest.java
  src/test/java/seedu/address/ui/VisitorViewTest.java
Labels: priority.High

#220 Update `addmeds` sequence diagram, Update PPP
  docs/DeveloperGuide.adoc
  docs/diagrams/AddmedsSequenceDiagram.pptx
  docs/images/AddmedsSequenceDiagram.png
  docs/team/snajef.adoc
Labels: priority.High

#184 Update UGDG for omegafishy PPP
  build/docs/html5/images/AddmhSequenceDiagram.png
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddmhSequenceDiagram.png
  docs/images/AddmhSequenceDiagram.png
  docs/images/ab4tohealthbase.png
  docs/team/omegafishy.adoc
  src/main/java/seedu/address/logic/commands/AddmhCommand.java
  src/main/java/seedu/address/model/medicalhistory/Timestamp.java
Labels: status.Ongoing, type.Task

#222 Refactor code
  docs/team/yuntongzhang.adoc
  src/main/java/seedu/address/logic/commands/AddDietCommand.java
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/logic/commands/CheckoutCommand.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/parser/CheckinCommandParser.java
  src/main/java/seedu/address/logic/parser/CheckoutCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/diet/Diet.java
  src/main/java/seedu/address/model/diet/DietCollection.java
  src/main/java/seedu/address/model/diet/DietType.java
  src/main/java/seedu/address/storage/XmlAdaptedDiet.java
  src/main/java/seedu/address/storage/XmlAdaptedDietCollection.java
  src/main/java/seedu/address/ui/DietView.java
  src/test/java/seedu/address/logic/commands/AddDietCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckinCommandTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddDietCommandParserTest.java
  src/test/java/seedu/address/model/diet/DietCollectionTest.java
  src/test/java/seedu/address/model/diet/DietTest.java
  src/test/java/seedu/address/storage/XmlAdaptedDietCollectionTest.java
  src/test/java/seedu/address/storage/XmlAdaptedDietTest.java
  src/test/java/seedu/address/testutil/DietBuilder.java
  src/test/java/seedu/address/ui/DietViewTest.java
  src/test/java/systemtests/RegisterCommandSystemTest.java
Labels: priority.High, type.Enhancement

#224 Fix typos in comments
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/guitests/guihandles/MedicationViewHandle.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#228 Update `addmeds` sequence diagram
  docs/diagrams/AddmedsSequenceDiagram.pptx
  docs/images/AddmedsSequenceDiagram.png
  docs/team/snajef.adoc
Labels: priority.High

#231 Update profile
  docs/AboutUs.adoc
  docs/images/jeffypie369.jpg
  docs/images/jeffypie369.png
Labels: priority.High

#225 Yuntong UG DG PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AdddietSequenceDiagram.pptx
  docs/images/AdddietSequenceDiagram.png
  docs/images/adddietcommand.png
  docs/team/yuntongzhang.adoc
  src/main/java/seedu/address/logic/commands/AddDietCommand.java
  src/test/java/seedu/address/model/diet/DietTest.java
  src/test/java/seedu/address/ui/DietViewTest.java
Labels: priority.High
